### ISSUE TITLE
Hardware interfacing

### ISSUE THREAD

**Issue by zachfi** [hb9tf/statusupdater#1]
Hi, I'm exploring Go projects for packet radio.  What hardware are you interfacing with here?  Are you publishing APRS stats or performing any radio communication here?

**Comment by roger-dodger** [comment]
Hi, `statusupdater` is not interfacing with any hardware. It fetches the last position for a list of callsigns from aprs.fi and updates the user status with its last position in Slack. The list of callsigns is fetched from the users' display names.
